### ISSUE TITLE
Esercizio

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/immagini#1]
Al momento non ho un esercizio da farti fare. Confido nella tua immaginazione per creare qualcosa

**Comment by Teodoro777** [comment]
Ok l'argomento lo scelgo io ma che tag devo includere?

Il martedì 3 maggio 2016, Fabio Z Tessitore <notifications@github.com> ha
scritto:

**Comment by FabioZTessitore** [comment]
Un esercizio con le immagini

Il martedì 3 maggio 2016, Teodoro <notifications@github.com> ha scritto:

**Comment by FabioZTessitore** [comment]
lo considero chiuso, ma togli quel tag font. Si usava mille anni fa

**Comment by Teodoro777** [comment]
Ahah e che ci metto?

**Comment by FabioZTessitore** [comment]
niente, un po' di pazienza

**Comment by Teodoro777** [comment]
Ok
